FROM almalinux:8

MAINTAINER Justas Balcas <jbalcas@caltech.edu>

RUN mkdir -p /opt/snmpmon/output/

RUN yum -y install git python39 python39-pyyaml

RUN cd /opt/snmpmon/ && git clone https://github.com/sdn-sense/snmpmon
RUN cd /opt/snmpmon/ && pip3 install -r requirements.txt || exit $?
RUN cd /opt/snmpmon/ && python3 setup.py install || exit $?

